Introduce stripe integration for 111 NFT
NetSepio/gateway pull request #147
Opened 2024-01-07 09:34 UTC by thisisommore

fix #146

2024-01-11 05:21 UTC, Shachindra approved these changes
LGTM

2024-01-11 05:27 UTC, Shachindra approved these changes

2024-01-11 05:27 UTC, Shachindra commented on api/v1/account/subscription/subscription.go
Rename?

stripe-webhook -> payment-webhook
111-nft -> erebrus

2024-01-11 05:27 UTC, Shachindra commented on api/v1/account/subscription/type.go
Buy111NFTResponse -> BuyErebrusNFTResponse

2024-01-11 05:27 UTC, Shachindra commented on migrations/000013_users_add_stripe_session_id.up.sql
Why this is inserted on USERS table?

2024-01-18 17:58 UTC, thisisommore commented on migrations/000013_users_add_stripe_session_id.up.sql
So we can track for which users wallet to mint nft to

2024-01-19 03:40 UTC, Shachindra requested changes
Please check the comments

2024-01-19 03:40 UTC, Shachindra commented on migrations/000013_users_add_stripe_session_id.up.sql
But doesn't this restricts the user to only be able to buy only 1 subscription? When we launch another subscription does this get updated? Also what'll happen in the case of failed/abandoned payment requests?

2024-01-22 05:25 UTC, thisisommore commented on migrations/000013_users_add_stripe_session_id.up.sql
Updated to support multiple subscriptions, also abandoned/failed payments are current not handled since stripe should just stop that and have time limit but we can keep record of the payment intents in db so in case of any issues we can always access it in db

2024-01-22 05:35 UTC, Shachindra approved these changes
LGTM

2024-01-22 14:35 UTC, merged